name: Build Bootstrap ZIP and attach to Release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Bootstrap ZIP and attach to Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install zip -y

      - name: Create ZIP
        run: zip -r flash-bootstrap-arm.zip .

      - name: Get Release URL
        id: get_release_url
        run: echo "::set-output name=url::$(jq -r '.release.upload_url' $GITHUB_EVENT_PATH)"

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release_url.outputs.url }}
          asset_path: ./flash-bootstrap-arm.zip
          asset_name: flash-bootstrap-arm.zip
          asset_content_type: application/zip
        env:
          TOKEN: ${{ secrets.TOKEN }}
